# Generated by Django 6.1 on 2026-08-22 05:17

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memory', '0002_alter_usermemory_embedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermemory',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=3072, null=True),
        ),
    ]
